#!/bin/bash

OK_STATE=0
WARNING_STATE=1
CRITICAL_STATE=2
UNKNOWN_STATE=3
EXPECTED_ARGS=4
E_BADARGS=65

private=$(ifconfig -a | awk '{print $2}'| grep '^192\.')

if [[ "$#" -ne "$EXPECTED_ARGS" || "$1" != '-i' || "$3" != '-b' ]]; then
    echo "Usage: `basename $0` -i IP -b BUCKET_NAME"
    exit ${UNKNOWN_STATE}
elif [ "$private" != "$2" ]; then	
    echo "Wrong private ip, I got $private. Please double check."
    exit ${UNKNOWN_STATE}
fi

`curl --silent -i http://$2:8098/riak?buckets=true > /tmp/riak_check_buckets`

if [ -f /tmp/riak_check_buckets ]; then
    bucket=`cat /tmp/riak_check_buckets | egrep "$4" | wc -l`
    if [[ "$bucket" -ge "1" ]]; then
	echo "OK - Riak answered that the bucket '$4' exists"
    rm -f /tmp/riak_check_buckets
	exit ${OK_STATE}
    else
	echo "CRITICAL - Bucket '$4' could not be found."
	exit ${CRITICAL_STATE}
    fi
else
    echo "Could not determine if the bucket exists. Please check /tmp/riak_check_buckets on target server."
    exit ${UNKNOWN_STATE}
fi
